.catch(err => {
console.log(err)
res.render(
'errorPage',
{ error: err.message }
)
}